version: "3.9"

services:
  SQLServer:
    image: "mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-16.04"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "1z2x3c!"
        ACCEPT_EULA: "Y"
