name: Code coverage
 
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
 
jobs:
  build:
    
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 5.0.x
      - name: Test
        run: dotnet test --no-restore --verbosity normal -c Release --no-build /p:CollectCoverage=true /p:CoverletOutput="$GITHUB_WORKSPACE/coverage/lcov.info" /p:MergeWith="$GITHUB_WORKSPACE/coverage/lcov.info" /p:CoverletOutputFormat=lcov
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
