name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
    - name: Install MyRestaurant.Models dependencies
      run: dotnet restore ./MyRestaurant.Core/MyRestaurant.Models.csproj
    - name: Install MyRestaurant.Core dependencies
      run: dotnet restore ./MyRestaurant.Core/MyRestaurant.Core.csproj
    - name: Install MyRestaurant.Services dependencies
      run: dotnet restore ./MyRestaurant.Core/MyRestaurant.Services.csproj
    - name: Install MyRestaurant.Business dependencies
      run: dotnet restore ./MyRestaurant.Business/MyRestaurant.Business.csproj
    - name: Install MyRestaurant.Api dependencies
      run: dotnet restore ./MyRestaurant.Api/MyRestaurant.Api.csproj
    - name: Build MyRestaurant.Models
      run: dotnet build ./MyRestaurant.Core/MyRestaurant.Models.csproj 
    - name: Build MyRestaurant.Core
      run: dotnet build ./MyRestaurant.Core/MyRestaurant.Core.csproj 
    - name: Build MyRestaurant.Services
      run: dotnet build ./MyRestaurant.Core/MyRestaurant.Services.csproj 
    - name: Build MyRestaurant.Business
      run: dotnet build ./MyRestaurant.Business/MyRestaurant.Business.csproj 
    - name: Build MyRestaurant.Api
      run: dotnet build ./MyRestaurant.Api/MyRestaurant.Api.csproj --configuration Release --no-restore
    - name: Test MyRestaurant.Api.Test
      run: dotnet test ./MyRestaurant.Api.Tests/MyRestaurant.Api.Tests.csproj --no-restore --verbosity normal
